base_app/urls.py
from django.urls import path
from base_app import views

app_name = 'base_app'

urlpatterns =[
path('',views.index, name = "index"),
path('home/',views.index, name = "tab1"),
path('register/',views.register, name = "register"),
path('register_customer_care/',views.register_customer_care, name = "register_customer_care"),
path('login/',views.user_login, name = "login"),
path('logout/',views.user_logout, name = "logout"),
path('delivery_agents/',views.delivery_agents, name = "delivery_agents"),
path('customer_care_executive/',views.customer_care_executive, name = "customer_care_executive"),
path('orders_list/',views.orders_list, name = "orders_list"),
path('customer_list/',views.customer_list, name = "customer_list"),
path('order_create/',views.order_create, name = "order_create"),
path('get_da_details/',views.get_da_details, name = "get_da_details"),
path('change_user_status/',views.change_user_status, name = "change_user_status"),
path('change_order_status/',views.change_order_status, name = "change_order_status"),
path('get_order_details/',views.get_order_details, name = "get_order_details"),
path('get_user_order_details/',views.get_user_order_details, name = "get_user_order_details"),
path('invoices/',views.invoices, name = "invoices"),
path('invoices_item/',views.invoices_item, name = "invoices_item"),
path('invoices_new/',views.invoices_new, name = "invoices_new"),





]

ideliver/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from django.contrib.
# from base_app import urls as base_app_urls
from base_app import views as base_app_views
# python -c "import django; print(django.get_version())"
urlpatterns = [
    # path('base_app/', base_app_urls),
    # path('', base_app_views.index1),
    path('',include('base_app.urls')),
    # path('base_app/',include('base_app.urls')),
    path('admin/', admin.site.urls),
    # url(r'^$', base_app_views.index, name='index'),
    # url(r'^base_app/',include('base_app.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

base_app/forms.py
from django import forms
from django.contrib.auth.models import User
from base_app.models import UserProfileInfo, Order, OrderItem, DaProfile
from base_app import dbconstants


class UserParentForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')
        # exclude = ['username']
class UserFormCustomer(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')
        exclude = ['username']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')
        exclude = ['username']

class UserFormDa(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'first_name', 'email', 'password')



class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('phone_primary', 'phone_secondary', 'location_area','location_sublocality','location_locality','location_city','location_pincode','profile_pic')


class UserProfileInfoFormDa(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('phone_primary', 'phone_secondary', 'location_area','location_sublocality','location_locality','location_city','location_pincode', 'profile_pic')

    def __init__(self, *args, **kwargs):
        super(UserProfileInfoFormDa, self).__init__(*args, **kwargs)
        self.fields['location_locality'].required = False
        self.fields['phone_secondary'].required = False

class DaProfileForm(forms.ModelForm):
    class Meta():
        model = DaProfile
        fields = ('user', 'driving_liscence_pic', 'pan_card_pic','rc_pic')

    def __init__(self, *args, **kwargs):
        super(DaProfileForm, self).__init__(*args, **kwargs)
        self.fields['user'].required = False
        self.fields['pan_card_pic'].required = False
        self.fields['rc_pic'].required = False

class OrderForm(forms.ModelForm):
    class Meta():
        model = Order
        fields = ( 'delivery_charges', 'status_note')
        exclude = ['delivery_charges', 'status_note']
    # def __init__(self, *args, **kwargs):
    #     super(OrderForm, self).__init__(*args, **kwargs)
    #     self.fields['user_delivery_agent'].required = False


    # customer_name = forms.CharField(label='Customer Name', max_length=50)
    # phone_primary = forms.CharField(max_length=10, label='Phone Number' )
    # location_sublocality = forms.CharField(max_length=80, label='Address' )
    # location_locality = forms.CharField(max_length=80, label='Locality')
    # location_city = forms.CharField(max_length=80,  label='City')
    # location_state = models.CharField(max_length=80, unique=False, default="KERALA")
    # location_pincode = forms.CharField(max_length=6, label='Pincode')
    # delivery_agent = forms.ModelChoiceField(queryset=UserProfileInfo.objects.prefetch_related('user').filter(user_type = dbconstants.USER_TYPE_DELIVERY_AGENT))
    # UserProfileInfo.objects.prefetch_related('user').filter(user_type = dbconstants.USER_TYPE_DELIVERY_AGENT)
    # forms.ModelChoiceField(queryset=User.objects.all().order_by('username'))
    # forms.CharField(max_length=80,  label='Delivery Agent')


class OrderItemForm(forms.ModelForm):

    class Meta():
        model = OrderItem
        fields = ('measurement_unit', 'item_name', 'item_quantity')
        exclude = ['measurement_unit','item_name','item_quantity']

base_app/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from base_app.forms import UserFormCustomer, UserProfileInfoForm, UserForm, UserFormDa, OrderForm, UserParentForm, UserProfileInfoFormDa, OrderItemForm, DaProfileForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.models import User
# from django.core.urlresolvers import reverse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.template.defaultfilters import slugify
import datetime
from base_app.utils import random_string_generator
import string
from base_app import constants, dbconstants
# from django.db import models
from base_app.models import UserProfileInfo, Order, OrderItem, ItemMeasuementUnit, DaProfile, OrderEvent
from django.core import serializers
# Create your views here.
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
import json
from base_app import smsbase
import re
from .filters import OrderFilter
# from itertools import izip




def change_user_status(request):

    print("came changestat")
    username = request.POST['username']
    user_status = request.POST['user_status']

    user_obj = User.objects.get(username=username)
    user_profile = UserProfileInfo.objects.get(user=user_obj)

    # user_profile = UserProfileInfo.objects.get(username=username)

    if user_status == "AT":
        print("useractive")
        user_status = dbconstants.USER_STATUS_DISABLED
    else:
        user_status = dbconstants.USER_STATUS_ACTIVE
        print("userinactive")
    user_profile.user_status = user_status
    user_profile.save()

    return HttpResponse(json.dumps({"SUCCESS":True, "RESPONSE_MESSAGE":"Status updated"}),
    content_type="application/json")



def customer_list(request):

    user_list = UserProfileInfo.objects.prefetch_related('user').filter(user_type = dbconstants.USER_TYPE_CONSUMER).order_by('-created_at')
    # user_list = User.objects.all().select_related('user_profile_info')

    # user_profile_list.

    user_list_final = []




    for user_temp in user_list:
        # print("caddd")
        user_meta_raw = User.objects.get(username=user_temp.user)
        # print(user_meta_raw.username)
        user_meta = {}
        user_meta['username'] = user_meta_raw.username
        #
        #
        # user_temp['profile_pic_absolute'] =  appendServerPath(user_temp['profile_pic'])
        # user_temp.profile_pic("aa","aa")
        # pic = user_temp.profile_pic
        # print(pic)
        user_parent_set = {}
        # user_parent_set['profile_pic'] = appendServerPath(user_temp.profile_pic)
        user_parent_set['user_meta'] = user_meta
        user_parent_set['user_profile'] = user_temp
        #
        user_list_final.append(user_parent_set)

    serialized_obj = serializers.serialize('json', user_list)

    print("sizeb:"+ str(user_list.count()))


    page = request.GET.get('page', 1)

    paginator = Paginator(user_list_final, 9)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    return render(request, 'base_app/customers.html',  {'state_list':dbconstants.STATE_LIST_DICT, 'users': users})


def index(request):

    print("klsklkl")

    # smsbase.sendOrderCreationMessage()

    order_count = Order.objects.all().count()
    order_delivered_count = 0
    delivery_boy_count = UserProfileInfo.objects.filter(user_type = dbconstants.USER_TYPE_DELIVERY_AGENT).count()

    customers_count  = UserProfileInfo.objects.filter(user_type = dbconstants.USER_TYPE_CONSUMER).count()
    customer_care_count  = UserProfileInfo.objects.filter(user_type = dbconstants.USER_TYPE_CUSTOMER_CARE_EXECUTIVE).count()
    print(customer_care_count)


    user_list = UserProfileInfo.objects.prefetch_related('user').filter(user_type = dbconstants.USER_TYPE_DELIVERY_AGENT)
    # user_list = User.objects.all().select_related('user_profile_info')

    # user_profile_list.

    user_list_final = []




    for user_temp in user_list:
        # print("caddd")
        user_meta_raw = User.objects.get(username=user_temp.user)
        # print(user_meta_raw.username)
        user_meta = {}
        user_meta['username'] = user_meta_raw.username
        #
        #
        # user_temp['profile_pic_absolute'] =  appendServerPath(user_temp['profile_pic'])
        # user_temp.profile_pic("aa","aa")
        pic = user_temp.profile_pic
        print(pic)
        user_parent_set = {}
        user_parent_set['profile_pic'] = appendServerPath(user_temp.profile_pic)
        user_parent_set['user_meta'] = user_meta
        user_parent_set['user_profile'] = user_temp
        #
        user_list_final.append(user_parent_set)
        # serialized_obja = serializers.serialize('json', [user_parent_set])
        # # # filter(user__username ='azr')
        # # # user_list = User.objects.filter(username ='azr')
        # dataa = {"aSomeModel_json": serialized_obj}
        # ("atitaa")
        # print(dataa)
        #
        #

    serialized_obj = serializers.serialize('json', user_list)



    # profile_check = UserProfileInfo.objects.filter(phone_primary=post_data["phone_primary"], user_type = dbconstants.USER_TYPE_CONSUMER)

    # Order.objects.prefetch_related('user_customer').prefetch_related('user_delivery_agent').all().order_by('-updated_at')




    page = request.GET.get('page', 1)

    paginator = Paginator(user_list_final, 100)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)


    today = datetime.date.today()

    base_dict = {"order_count":order_count,"customer_care_count": customer_care_count, "delivery_boy_count":delivery_boy_count, "order_delivered":order_delivered_count, "customers_count":customers_count, "delivery_agents":users, 'pic_server_prefix':'http://http://167.71.126.94:8000/media/' }
    return render(request, 'base_app/index.html', context = base_dict)

@login_required
def delivery_agents(request):
    # user_profile_list = UserProfileInfo.objects.filter(user_type =dbconstants.DELIVERY_AGENT)
    # user_list = User.objects.filter(user_profile_info__user_type = dbconstants.DELIVERY_AGENT)
    # user_list = UserProfileInfo.objects.all().select_related('user')
    user_list = UserProfileInfo.objects.prefetch_related('user').filter(user_type = dbconstants.USER_TYPE_DELIVERY_AGENT).order_by('-updated_at')
    # entry_list = len(UserProfileInfo.objects.all())
    # print(str("ds")

    # user_list = User.objects.all().select_related('user_profile_info')

    # user_profile_list.


    user_list_final = []






    for user_temp in user_list:
        # print("caddd")
        user_meta_raw = User.objects.get(username=user_temp.user)
        # print(user_meta_raw.username)
        user_meta = {}
        user_meta['username'] = user_meta_raw.username
        #
        #
        # user_temp['profile_pic_absolute'] =  appendServerPath(user_temp['profile_pic'])
        # user_temp.profile_pic("aa","aa")
        pic = user_temp.profile_pic
        # print(pic)
        user_parent_set = {}
        user_parent_set['profile_pic'] = appendServerPath(user_temp.profile_pic)
        user_parent_set['user_meta'] = user_meta
        user_parent_set['user_profile'] = user_temp
        #
        user_list_final.append(user_parent_set)
        # serialized_obja = serializers.serialize('json', [user_parent_set])
        # # # filter(user__username ='azr')
        # # # user_list = User.objects.filter(username ='azr')
        # dataa = {"aSomeModel_json": serialized_obj}
        # ("atitaa")
        # print(dataa)
        #
        #

    serialized_obj = serializers.serialize('json', user_list)
    # filter(user__username ='azr')
    # user_list = User.objects.filter(username ='azr')
    # dataa = {"SomeModel_json": serialized_obj}
    # print("titaa")
    # print(dataa)
    # print("sizea:"+ str(user_profile_list.count()))
    print("sizeb:"+ str(user_list.count()))


    page = request.GET.get('page', 1)

    paginator = Paginator(user_list_final, 9)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    return render(request, 'base_app/delivery_agents.html',  {'state_list':dbconstants.STATE_LIST_DICT, 'users': users, 'pic_server_prefix':'http://167.71.126.94:8000/media/' })

def invoices(request):
    return render(request, 'base_app/invoices.html',  { })


def invoices_new(request):
    return render(request, 'base_app/invoices_new.html',  { })


def invoices_item(request):
    return render(request, 'base_app/invoices_item.html',  { })

@login_required
def customer_care_executive(request):
    # user_profile_list = UserProfileInfo.objects.filter(user_type =dbconstants.DELIVERY_AGENT)
    # user_list = User.objects.filter(user_profile_info__user_type = dbconstants.DELIVERY_AGENT)
    # user_list = UserProfileInfo.objects.all().select_related('user')
    user_list = UserProfileInfo.objects.prefetch_related('user').filter(user_type = dbconstants.USER_TYPE_CUSTOMER_CARE_EXECUTIVE).order_by('-updated_at')
    # user_list = User.objects.all().select_related('user_profile_info')

    # user_profile_list.

    print(len(user_list))

    user_list_final = []




    for user_temp in user_list:
        # print("caddd")
        user_meta_raw = User.objects.get(username=user_temp.user)
        # print(user_meta_raw.username)
        user_meta = {}
        user_meta['username'] = user_meta_raw.username
        #
        #

templates/base_app/base.html
<!doctype html> {% load staticfiles %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Smart Order | CRM</title>
    <link rel="icon" type="image/png" sizes="32x32" href="../static/images/favicon_32x32.png">
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="../static/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:500,700&display=swap" rel="stylesheet">
    <script src="../static/js/jquery-3.4.1.js"></script>
    <link rel="stylesheet" href="../static/css/main.css">
    <script src="../static/js/delivery_agents.js"></script>


    <!-- window.location.replace($('#login_success').val()); -->

</head>
<!-- window.location.replace("{% url 'base_app:login' %}").val()); -->

<body onload="loginCheck('{{ user.is_authenticated }}');">
    <input type="hidden" id="login_url" value="{% url 'base_app:login' %}" />
    <div class="web_layout">
        <nav class="navbar navbar-expand-lg navbar-light fixed-top navbar_fixed_top">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav mr-auto active float-right">
                    {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Welcome: {{ user.username }}
                </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                            <a class="dropdown-item" href="#">Link 1</a>
                            <a class="dropdown-item" href="#">Another 2</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'base_app:logout' %}"> Logout</a> {% else %}
                            <a class="dropdown-item" href="{% url 'base_app:login' %}">Login</a> {% endif %}

                        </div>
                    </li>
                </ul>

            </div>
        </nav>
        <!-- SIDEBAR LEFT -->
        <div class="left_sidebar">
            <div class="logo"><img src="../static/images/logo.png" class="w-100 mt_20"></div>
            <ul class="sidebar-nav">
                <li role="presentation">
                    <a href="{% url 'base_app:index' %}"> <span class="icon_set icon-home menu_icon"></span> Home </a>
                </li>

                {% if user.is_authenticated %}
                <li role="presentation">
                    <a href="{% url 'base_app:delivery_agents' %}"> <span class="icon_set icon-avatar menu_icon"></span> Delivery Agents</a>
                </li>
                <li role="presentation">
                    <a href="{% url 'base_app:orders_list' %}"> <span class="icon_set icon-package menu_icon"></span> Orders</a>
                </li>
                <li role="presentation">
                    <a href="{% url 'base_app:customer_list' %}"> <span class="icon_set icon-group menu_icon"></span> Customer</a>
                </li>
                <li role="presentation">
                    <a href="{% url 'base_app:customer_care_executive' %}"> <span class="icon_set icon-group menu_icon"></span> Customer Care</a>
                </li>
                <li role="presentation">
                    <a href="{% url 'base_app:invoices' %}"> <span class="icon_set icon-settings menu_icon"></span> Invoices</a>
                </li>
                {% else %}
                <li role="presentation"><a href="{% url 'base_app:login' %}">Login</a></li>
                {% endif %}

            </ul>
        </div>

        <div id='alert'>
        </div>

        <div class="right_sidebar">
            <!-- <div class="top_header">
                {% if user.is_authenticated %}
                <div class="col-md-10 float-left pl_10">Welcome: {{ user.username }}</div>
                <div class="col-md-2 float-right">

                    <a class="text-right w-100 float-right" href="{% url 'base_app:logout' %}"> Logout</a> {% else %}

                    <a href="{% url 'base_app:login' %}">Login</a> {% endif %}
                </div>
            </div> -->
            <div class="main_contain">

                {% block body_block %} {% endblock %}

            </div>
        </div>
    </div>
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

templates/base_app/hello.html
hello

templates/base_app/index1.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <meta charset="utf-8">
  <title> static tests</title>
  <link rel="stylesheet" href="{% static "css/base_style.css" %} ">
</head>
<body>
<!-- <script src= src="{% static "js/delivery_agents.js" %}" > </script> -->
<h1>{{test_var}}</h1>
<p>This is another paragraph.</p>
<img src="{% static "images/angrybat.jpg" %}" alt="Not loaded" >
</body>
</html>

templates/base_app/invoices.html
{% extends "base_app/base.html" %} {% block body_block %}
<input type="hidden" id="ul_user_status" value="{% url 'base_app:change_user_status' %}" />
<div class="float-left col-md-12 no-padding">

<div class="common_container">
    <div class="second_header">
        <ul class="page_nav">
            <li><a href="{% url 'base_app:invoices' %}" class="page_nav_active">Invoices</a></li>
            <li> <a href="{% url 'base_app:invoices_new' %}"> Items</a> </li>
        </ul>
        <button type="button" class="mt_10 btn primary_btn float-right mr_15">Create Invoice</button>
    </div>
    <div class="content_wrapper">
        <div class="filter_container">
            <div class="form-group col-md-2 pl_0 float-left">
                <label for="">Invoices Status</label>
                <select class="form-control" name="">
                    <option value=""> All </option>
                    <option value=""> Draft </option>
                </select>
            </div>
            <div class="form-group col-md-2 pl_0 float-left">
                <label for="">Invoice Id</label>
                <input type="text" class="form-control" id="item_name" name="" placeholder="Search by Id">
            </div>
            <div class="form-group col-md-2 pl_0 float-left"> <button type="button" class="btn float-left mr_15 mt_20">Search</button> </div>
        </div> <!-- ==== End of Filter Container ======================-->

        <div class="table-responsive table-striped table-hover mt_20 float-left">
                <table class="table">
                    <thead>
                      <tr>
                        <th>Date</th>
                        <th>Invoice ID</th>
                        <th>Order No</th>
                        <th>Due Date </th>
                        <th>Amount Name</th>
                        <th>Customer</th>
                        <th>Status</th>
                      </tr>
                    </thead>
                    <tbody>
                        <tr>      
                          <td style="">  12/12/2020 </td>
                          <td style=""> <a href="{% url 'base_app:invoices_new' %}" class="items_link"> ASD23232</a>  </td>
                          <td style="">  OD23243AADKkd22 </td>
                          <td style="">  12/05/2020 </td>
                          <td style="">  ₹ 3,234.00 </td>
                          <td style="">  Jhon Miller </td>
                          <td style="">  <span class="item_status">Draft</span>  </td>
                        </tr>
                        <tr>        
                            <td style="">  12/12/2020 </td>
                            <td style="">  <a href="#" class="items_link">ASZ2323</a> </td>
                            <td style="">  OD23243AADKkd22 </td>
                            <td style="">  12/05/2020 </td>
                            <td style="">  ₹ 3,234.00 </td>
                            <td style="">  Jhon Miller </td>
                            <td style="">  <span class="item_status">Draft</span>  </td>
                        </tr>
                        <tr>        
                            <td style="">  12/12/2020 </td>
                            <td style="">  <a href="#" class="items_link">ASZ2323</a> </td>
                            <td style="">  OD23243AADKkd22 </td>
                            <td style="">  12/05/2020 </td>
                            <td style="">  ₹ 3,234.00 </td>
                            <td style="">  Jhon Miller </td>
                            <td style="">  <span class="item_status">Draft</span>  </td>
                        </tr>
                        <tr>        
                            <td style="">  12/12/2020 </td>
                            <td style="">  <a href="#" class="items_link">ASZ2323</a> </td>
                            <td style="">  OD23243AADKkd22 </td>
                            <td style="">  12/05/2020 </td>
                            <td style="">  ₹ 3,234.00 </td>
                            <td style="">  Jhon Miller </td>
                            <td style="">  <span class="item_status">Draft</span>  </td>
                        </tr>
                    </tbody>
                  </table>
            </div>


    </div><!-- ==== == End of Content Wrapper Container ======================-->
     

</div>


</div>


{% endblock %}

templates/base_app/invoices_item.html
{% extends "base_app/base.html" %} {% block body_block %}
<input type="hidden" id="ul_user_status" value="{% url 'base_app:change_user_status' %}" />
<div class="float-left col-md-12 no-padding">

<div class="common_container">
    <div class="second_header">
        <ul class="page_nav">
                <li><a href="{% url 'base_app:invoices' %}" >Invoices</a></li>
                <li> <a href="{% url 'base_app:invoices_item' %}" class="page_nav_active"> Items</a> </li>
        </ul>
        <button type="button" class="mt_10 btn primary_btn float-right mr_15">Create Invoice</button>
    </div>
    <div class="content_wrapper">
        <div class="filter_container p_15">
            <div class="form-group col-md-2 pl_0 float-left">
                <label for="">Invoices Status</label>
                <select class="form-control" name="">
                    <option value=""> All </option>
                    <option value=""> Draft </option>
                </select>
            </div>
            <div class="form-group col-md-2 pl_0 float-left">
                <label for="">Invoice Id</label>
                <input type="text" class="form-control" id="item_name" name="" placeholder="Search by Id">
            </div>
            <div class="form-group col-md-2 pl_0 float-left"> <button type="button" class="btn float-left mr_15 mt_20">Search</button> </div>
        </div> <!-- ==== End of Filter Container ======================-->
    </div><!-- ==== == End of Content Wrapper Container ======================-->
     

</div>


</div>


{% endblock %}

templates/base_app/order_create.html
{% extends "base_app/base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="jumbotron">


  {% if registered %}
  <h1>Registerion successful!</h1>
  {% else %}
  <h1>Create Order</h1>
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{order_form.as_p}}

    <input type="submit" name="" value="Register">
  </form>
  {% endif %}

</div>

{% endblock %}

templates/base_app/registration.html
{% extends "base_app/base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="jumbotron">


  {% if registered %}
  <h1>Registerion successful!</h1>
  {% else %}
  <h1>Delivery Agent Registation</h1>
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{user_form.as_p}}
    {{profile_form.as_p}}

    <input type="submit" name="" value="Register">
  </form>
  {% endif %}

</div>

{% endblock %}